interface Member {
    title: string;
    jobTitle: string | null;
    description: string;
    imagePath: string;
}

export const OFFICIAL_MEMBERS: Member[] = [
    {
        imagePath: '/images/member-1.jpeg',
        title: 'Professor Maged Shebaita',
        jobTitle: 'The Founder',
        description: 'Professor Maged Shebaita is a distinguished Professor of Transnational Law with over two decades of experience in international commercial arbitration and Islamic finance. His illustrious career began in the Egyptian Judiciary, where he rose to the position of Chief Justice in the Administrative Court of Appeals. Beyond his judicial role, Professor Shebaita was a pivotal member of the Constituent Assembly responsible for drafting the 2012 Egyptian Constitution and served as a legal adviser to several high-ranking officials, including the Egyptian President, Minister of Foreign Affairs, Minister of Internal Affairs, Minister of Justice, and Minister of Finance.     Internationally, Professor Shebaita has made significant contributions as a member of some of the world\'s most prestigious arbitration centers, including the Chartered Institute of Arbitrators (CIArb), the London Court of International Arbitration (LCIA), the Cairo Regional Centre for International Commercial Arbitration (CRCICA), and the International Islamic Centre for Reconciliation and Arbitration (IICRA Extra). His global influence was further solidified through his role as Secretary General of the Organisation of Islamic Cooperation Arbitration Centre, the second-largest international organization after the United Nations. An eminent international arbitrator and counsel, Professor Shebaita has handled numerous high-profile cases worldwide. His expertise in arbitration was honed through an LLM in International Commercial Arbitration from University College London (UCL). He has also served as Senior Legal Counsel at GSC Solicitors in London, where he specializes in Alternative Dispute Resolution (ADR) and Islamic finance. At GSC Solicitors, Professor Shebaita combines his legal expertise with marketing and training initiatives, fostering global joint ventures and supporting Dubai\'s initiative to establish an Islamic Arbitration Centre in London. He is also actively involved in launching a training course for Pakistani judges on Islamic finance. Academically, Professor Shebaita holds two PhDs in Comparative Constitutional Law and Islamic Law and is currently preparing to complete his third PhD in Comparative Law at the School of Oriental and African Studies (SOAS), University of London. His extensive knowledge and experience make him a leading authority in his fields of expertise, both in academia and practice.'
    },
    {
        imagePath: '/images/member-2.jpeg',
        title: 'Zachary R. Calo',
        jobTitle: null,
        description: 'Zachary R. Calo is Full Professor of Law and Founding Professor at Hamad bin Khalifa University in Doha, Qatar, where he has been a faculty member since 2015.  He is also Professor of Law (Adjunct) at the University of Notre Dame Australia, Visiting Professor at The Open University (UK), Central Asia Research Fellow and Visiting Professor at Tashkent State University of Law (Uzbekistan), Adjunct Professor at Northwestern University in Qatar, and Lecturer at the Qatar Olympic Academy.  Editor of 2 books and author of 80 articles, he is a leading authority on international dispute resolution, sports law, and religion and law.  He previously taught at Valparaiso University School of Law, Notre Dame Law School, and DePaul College of Law in the United States.  He also maintains an active legal and dispute resolution practice as Senior Counsel with McNair International (London & Doha), Of Counsel Sports Law with Schelstraete Equine Law (Amsterdam & Doha), and as Co-Founder and International Mediator with Gulf Mediation, a leading boutique provider of commercial mediation services in the Middle East.  He is a member of international dispute resolution panels at Sport Resolutions UK and the Qatar Sports Arbitration Tribunal, and is an Officer of the International Bar Association Mediation Committee and Secretary of the Ethics Committee of the International Mediation Institute.  A member of the Washington DC Bar and a CEDR-accredited mediator, he previously practiced banking and commercial law with Buckley, LLP.  He holds a J.D. from the University of Virginia School of Law, B.A. and M.A. from The Johns Hopkins University, Ph.D. from the University of Pennsylvania, M.A. from the University of Virginia, and an LLM in Dispute Resolution from the Straus Institute at Pepperdine University School Law.'
    }
];